name: Build Base Images

on:
  workflow_call:
    inputs:
      PLATFORMS:
        type: string
        default: linux/amd64
        required: false
      POSTGRESQL_VERSION:
        type: string
        default: 13
        required: false
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
      GH_TOKEN:
        required: true

concurrency:
  group: ci-build-base-images-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

env:
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_NAME_GHCR: ghcr.io/${{ github.repository }}
  IMAGE_NAME_DOCKER: deineagenturug/gvm
  IMAGE_NAME_OCIR: fra.ocir.io/fraj3sqdynbw/gvm
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  POSTGRESQL_VERSION: ${{ inputs.POSTGRESQL_VERSION }}

permissions:
  id-token: write
  actions: read
  contents: read
  packages: write
  pull-requests: read
  security-events: write

jobs:

  building_build_images_step_1:
    name: Image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        IMAGE:
          - base
          - gsa

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ./.checkupdates/
          key: ${{ runner.os }}-gvm-version-check-v2-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-gvm-version-check-v2-

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
          driver-opts: |
            image=deineagenturug/buildkit:latest

      - name: Inspect builder
        run: |
          echo "Name        : ${{ steps.buildx.outputs.name }}"
          echo "Endpoint    : ${{ steps.buildx.outputs.endpoint }}"
          echo "Status      : ${{ steps.buildx.outputs.status }}"
          echo "Flags       : ${{ steps.buildx.outputs.flags }}"
          echo "Platforms   : ${{ steps.buildx.outputs.platforms }}"

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get Latest Versions
        run: |
          echo 'GREENBONE_RELEASES<<EOF' >> $GITHUB_ENV
          cat ./.checkupdates/latest_version | sed 's/=v/=/g' >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Build and push Docker image ${{ matrix.BUILD_NAME }}
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: ${{ inputs.PLATFORMS }}
          push: true
          cache-from: |
            ${{ env.IMAGE_NAME_DOCKER }}-build:build_${{ matrix.IMAGE }}
          file: ./Dockerfiles/build_${{ matrix.IMAGE }}.Dockerfile
          tags: |
            ${{ env.IMAGE_NAME_DOCKER }}-build:build_${{ matrix.IMAGE }}
          labels: |
            ${{ env.GREENBONE_RELEASES }}
            POSTGRESQL_VERSION=${{ env.POSTGRESQL_VERSION }}
          build-args: |
            ${{ env.GREENBONE_RELEASES }}
            POSTGRESQL_VERSION=${{ env.POSTGRESQL_VERSION }}
            BUILDKIT_INLINE_CACHE=1

  building_build_images_step_2:
    name: Image
    needs: building_build_images_step_1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        IMAGE:
          - gvm_libs
          - gsad

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ./.checkupdates/
          key: ${{ runner.os }}-gvm-version-check-v2-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-gvm-version-check-v2-

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
          driver-opts: |
            image=deineagenturug/buildkit:latest

      - name: Inspect builder
        run: |
          echo "Name        : ${{ steps.buildx.outputs.name }}"
          echo "Endpoint    : ${{ steps.buildx.outputs.endpoint }}"
          echo "Status      : ${{ steps.buildx.outputs.status }}"
          echo "Flags       : ${{ steps.buildx.outputs.flags }}"
          echo "Platforms   : ${{ steps.buildx.outputs.platforms }}"

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get Latest Versions
        run: |
          echo 'GREENBONE_RELEASES<<EOF' >> $GITHUB_ENV
          cat ./.checkupdates/latest_version | sed 's/=v/=/g' >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Build and push Docker image ${{ matrix.BUILD_NAME }}
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: ${{ inputs.PLATFORMS }}
          push: true
          cache-from: |
            ${{ env.IMAGE_NAME_DOCKER }}-build:build_${{ matrix.IMAGE }}
          file: ./Dockerfiles/build_${{ matrix.IMAGE }}.Dockerfile
          tags: |
            ${{ env.IMAGE_NAME_DOCKER }}-build:build_${{ matrix.IMAGE }}
          labels: |
            ${{ env.GREENBONE_RELEASES }}
            POSTGRESQL_VERSION=${{ env.POSTGRESQL_VERSION }}
          build-args: |
            ${{ env.GREENBONE_RELEASES }}
            POSTGRESQL_VERSION=${{ env.POSTGRESQL_VERSION }}
            BUILDKIT_INLINE_CACHE=1

  building_build_images_step_3:
    name: Image
    needs: building_build_images_step_2
    runs-on: ubuntu-latest
    strategy:
      matrix:
        IMAGE:
          - gvmd
          - openvas_smb
          - openvas_scanner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ./.checkupdates/
          key: ${{ runner.os }}-gvm-version-check-v2-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-gvm-version-check-v2-

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
          driver-opts: |
            image=deineagenturug/buildkit:latest

      - name: Inspect builder
        run: |
          echo "Name        : ${{ steps.buildx.outputs.name }}"
          echo "Endpoint    : ${{ steps.buildx.outputs.endpoint }}"
          echo "Status      : ${{ steps.buildx.outputs.status }}"
          echo "Flags       : ${{ steps.buildx.outputs.flags }}"
          echo "Platforms   : ${{ steps.buildx.outputs.platforms }}"

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get Latest Versions
        run: |
          echo 'GREENBONE_RELEASES<<EOF' >> $GITHUB_ENV
          cat ./.checkupdates/latest_version | sed 's/=v/=/g' >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Build and push Docker image ${{ matrix.BUILD_NAME }}
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: ${{ inputs.PLATFORMS }}
          push: true
          cache-from: |
            ${{ env.IMAGE_NAME_DOCKER }}-build:build_${{ matrix.IMAGE }}
          file: ./Dockerfiles/build_${{ matrix.IMAGE }}.Dockerfile
          tags: |
            ${{ env.IMAGE_NAME_DOCKER }}-build:build_${{ matrix.IMAGE }}
          labels: |
            ${{ env.GREENBONE_RELEASES }}
            POSTGRESQL_VERSION=${{ env.POSTGRESQL_VERSION }}
          build-args: |
            ${{ env.GREENBONE_RELEASES }}
            POSTGRESQL_VERSION=${{ env.POSTGRESQL_VERSION }}
            BUILDKIT_INLINE_CACHE=1
